version: '3'

services:
  php:
    container_name: "php-fpm"
    build:
      context: ./php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ${APP_FOLDER}:/var/www
    ports:
      - 5000:8000

  node:
    container_name: "docker-node"
    user: "node"
    environment:
      - NODE_ENV=production
    build:
      context: ./node
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
