version: '3'

services:
  php:
    container_name: "php-fpm"
    build:
      context: ./php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ${APP_FOLDER}:/var/www

  nginx:
    container_name: "nginx"
    build:
      context: ./nginx
    volumes:
      - ${APP_FOLDER}:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - "80:80"

  node:
    container_name: "docker-node"
    user: "node"
    environment:
      - NODE_ENV=production
    build:
      context: ./node
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
